### ISSUE TITLE
Klusterlet CR generated from clusteradm join command contains invalid externalServerURLs for Oracle Kubernetes Engine cluster

### ISSUE THREAD

**Issue by mikeshng** [open-cluster-management-io/clusteradm#274]
In an Oracle Kubernetes Engine cluster, the cluster-info config map:
```
kubectl -n kube-public get cm cluster-info -o yaml
```
contains
```
server: 1.2.3.4:6443 # without the https://
```
this might have cause the clusteradm to generate a Klusterlet CR with the spec of 
```
    externalServerURLs:
    - url: 1.2.3.4:6443 # without the https://
```

This fails the spoke agent validation in https://github.com/open-cluster-management-io/registration/blob/release-0.8/pkg/spoke/spokeagent.go#L435-L442
causing the managed cluster not to proceed with the registration process.

The workaround is modify the klusterlet CR by appending the `https://` and the registration went through successfully.

```
kubectl version: v1.23.7+1
clusteradm version:
client          version :v0.3.1
server release  version :v1.23.4
default bundle  version :0.8.0
Kubernetes version: v1.23.4
Distribution: Oracle Kubernetes Engine
```

Reported by @hyder

**Comment by hyder** [comment]
Hi,

Sorry for the delay.

Please find troubleshooting steps for this issue:

```
[opc@mc-operator ~]$ kubectl -n open-cluster-management-agent get pods
NAME                                           READY   STATUS             RESTARTS      AGE
klusterlet-registration-agent-dd8d4889-79ngn   0/1     CrashLoopBackOff   2 (15s ago)   49s

kubectl -n open-cluster-management-agent logs -f klusterlet-registration-agent-dd8d4889-79ngn

F1014 10:47:36.421943       1 spokeagent.go:132] "10.23.0.22:6443" is invalid
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
        k8s.io/klog/v2@v2.60.1/klog.go:860 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x3b298c0, 0x3, 0x0, 0xc0007a78f0, 0x1, {0x2eab442?, 0x7f8b8019cf18?}, 0x10?, 0x0)
        k8s.io/klog/v2@v2.60.1/klog.go:825 +0x686
k8s.io/klog/v2.(*loggingT).printDepth(0x3b298c0, 0x282ecd0?, 0x0, {0x0, 0x0}, 0x2828ae0?, {0xc000a3cbb0?, 0x1, 0x1})
        k8s.io/klog/v2@v2.60.1/klog.go:608 +0x1d3
k8s.io/klog/v2.(*loggingT).print(...)
        k8s.io/klog/v2@v2.60.1/klog.go:590
k8s.io/klog/v2.Fatal(...)
        k8s.io/klog/v2@v2.60.1/klog.go:1490

kubectl get klusterlet -o yaml

apiVersion: v1
items:
- apiVersion: operator.open-cluster-management.io/v1
  kind: Klusterlet
  metadata:
    creationTimestamp: "2022-10-14T10:46:12Z"
    finalizers:
    - operator.open-cluster-management.io/klusterlet-cleanup
    generation: 2
    name: klusterlet
    resourceVersion: "9709"
    uid: 913a0e5d-9b78-49ab-8cc5-9149dfd67b56
  spec:
    clusterName: melbourne
    deployOption:
      mode: ""
    externalServerURLs:
    - url: 10.23.0.22:6443
    namespace: open-cluster-management-agent
    nodePlacement: {}
    registrationImagePullSpec: quay.io/open-cluster-management/registration:v0.8.0
    workImagePullSpec: quay.io/open-cluster-management/work:v0.8.0
```    

After editing url and prepending `https://`, a new pod is created:

```
NAME                                             READY   STATUS              RESTARTS      AGE
klusterlet-registration-agent-79d55d46c6-ht5sz   0/1     ContainerCreating   0             4s
klusterlet-registration-agent-dd8d4889-79ngn     0/1     CrashLoopBackOff    5 (43s ago)   4m6s


kubectl logs -f klusterlet-registration-agent-79d55d46c6-ht5sz

I1014 10:50:45.948961       1 event.go:285] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"open-cluster-management-agent", Name:"klusterlet-registration-agent", UID:"a16f0241-18a2-4d69-9261-fd89e02f42ed", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'ManagedClusterCreated' Managed cluster "melbourne" created on hub
I1014 10:50:45.987565       1 event.go:285] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"open-cluster-management-agent", Name:"klusterlet-registration-agent", UID:"a16f0241-18a2-4d69-9261-fd89e02f42ed", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'CSRCreated' A csr "melbourne-ldhsd" is created
```

Accept the join request:

```
kubectl get csr | grep melbourne

melbourne-ldhsd   3m11s   kubernetes.io/kube-apiserver-client           system:serviceaccount:open-cluster-management:cluster-bootstrap   <none>              Pending

clusteradm accept --clusters melbourne
CSR melbourne-ldhsd approved
set hubAcceptsClient to true for managed cluster melbourne
```

**Comment by hyder** [comment]
Hi, any update on this?

**Comment by mikeshng** [comment]
@qiujian16 not sure if this issue should just be doc with something like this:

For Oracle Kubernetes Engine cluster, first ensure that the `cluster-info` ConfigMap in `kube-public` namespace to contains `server: https://`. If the `https://` portion is missing, update the ConfigMap prior to running the `clusteradm init` command.

**Comment by qiujian16** [comment]
I think we need a preflight check, we check the info at first, if there is none, we might prompt a warning or let user to input the url.

**Comment by qiujian16** [comment]
cc @ycyaoxdu

**Comment by ycyaoxdu** [comment]
@hyder hi, changes merged. please let me know if there is still any concerns.

**Comment by xuezhaojun** [comment]
Hello, everyone @qiujian16 @ycyaoxdu, as I'm reviewing the document of the `join` process. I have a question about the above change: 

If the URL doesn't pass the validation, could we skip it rather than return it with an error? Because in this case, the `SpokeExternalServerURLs` can be empty and won't block the `join` process.

I feel giving a warning msg is more friendly than blocking the join process and asking the user to modify their configmap(And they may not want to because the configmap cluster-info may already be used in their bussiness).

**Comment by xuezhaojun** [comment]
@ycyaoxdu Hello, YuChen, please take a look at the above PR when you have time, thanks!
